# Generated by Django 3.2.13 on 2022-06-13 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('telefono', models.IntegerField(max_length=9, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=40, verbose_name='Direccion')),
            ],
        ),
        migrations.DeleteModel(
            name='Productos',
        ),
    ]
