# Generated by Django 3.2.13 on 2022-06-13 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptienda', '0002_auto_20220612_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de Categoría')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='Nombre de Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('nombre', models.CharField(max_length=6, verbose_name='nombre')),
                ('codigo_barra', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='codigo_barra')),
                ('edad_animal', models.IntegerField(max_length=2, verbose_name='Edadanimal')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptienda.categoria')),
            ],
        ),
    ]
